name: deploy

on:
  push:
    branches:
    - develop
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install yarn
      run: sudo npm install -g yarn

    - name: Install
      run: make install

    - name: Deploy
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_S3_BUCKET:  ${{ secrets.AWS_S3_BUCKET }}
      run: make deploy
